---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tlb-controller.serviceAccountName" . }}
  labels:
    {{- include "tlb-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tlb-controller.fullname" . }}
  labels:
    {{- include "tlb-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - update
      - patch
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs:
      - create
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - create
      - update
      - patch
      - watch
  - apiGroups: ["tlb.io"]
    resources:
      - clustertunnelclasses
      - tunnelclasses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tlb-controller.fullname" . }}
  labels:
    {{- include "tlb-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tlb-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tlb-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
