---
apiVersion: tlb.io/v1alpha1
kind: ClusterTunnelClass
metadata:
  name: cloudflare
spec:
  cloudflare:
    accountId: b960d3e903036d4cd5350a4ebf815c4d
    apiTokenRef:
      name: cloudflare-api-key
      namespace: default
      key: token

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
type: Opaque
stringData:
  token: Sq2z0C-4vIEG70H_MMgOtoBG5MkhxZRxYpL4fv9r

---
# Multi-port service with TLS termination using NetBird format
apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
  annotations:
    tlb.io/dns: multi.432372253.xyz
    tlb.io/map-ports: "80:8080, 443/tls:8080"
spec:
  type: LoadBalancer
  loadBalancerClass: tlb.io/cloudflare
  selector:
    app: multi-port-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-port-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-port-app
  template:
    metadata:
      labels:
        app: multi-port-app
    spec:
      containers:
        - name: web-server
          image: nginx:latest
          ports:
            - containerPort: 8080