---
# Example configuration for Cloudflare Quick tunnel mode
# Quick mode is automatically selected when no API credentials (apiTokenRef/accountId) are provided
apiVersion: tlb.io/v1alpha1
kind: ClusterTunnelClass
metadata:
  name: cloudflare-quick
spec:
  cloudflare:
    # Quick mode: no API credentials needed (omit apiTokenRef and accountId)
    image: cloudflare/cloudflared:latest

---
# Example service using the quick tunnel mode
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world-quick
  annotations:
    # Note: DNS annotation is ignored in quick mode since we can't manage DNS without API credentials
    # tlb.io/dns: hello-quick.example.com
    tlb.io/protocol: "http"
spec:
  type: LoadBalancer
  loadBalancerClass: tlb.io/cloudflare-quick
  selector:
    app: nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx-hello-world
          image: nginx:latest
          ports:
            - containerPort: 80