---
apiVersion: tlb.io/v1alpha1
kind: ClusterTunnelClass
metadata:
  name: cloudflare-quick
spec:
  # Quick mode: no API credentials needed (omit apiTokenRef and accountId)
  cloudflare: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world-quick
  annotations:
    tlb.io/protocol: "http"
spec:
  type: LoadBalancer
  loadBalancerClass: tlb.io/cloudflare-quick
  selector:
    app: nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx-hello-world
          image: nginx:latest
          ports:
            - containerPort: 80
