---
apiVersion: tlb.io/v1alpha1
kind: ClusterTunnelClass
metadata:
  name: netbird
spec:
  netbird:
    managementUrl: https://netbird.example.com
    setupKeyRef:
      name: netbird-setup-key
      namespace: default
      key: setupKey

---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-setup-key
type: Opaque
stringData:
  setupKey: 76A5AE81-1E3D-4207-9939-82EC1A97BF0F

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
spec:
  type: LoadBalancer
  loadBalancerClass: tlb.io/netbird
  selector:
    app: nginx-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx-hello-world
          image: nginx:latest
          ports:
            - containerPort: 80
